# Generated by Django 6.0 on 2026-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_address_student_city_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
